const books = [
    /*First book*/
    {
        id: 1,
        tittle: "Dar anomalii. Księga 1",
        author: "Paweł Zbroszczyk",
        coverImage: "/covers/id1.jpg",
        cost: 66.33,
        description: "Uważaj na to, co czy\n\nnisz. Biel twoich piór nie jest wieczna, a w każdym sercu czai się mrok gotowy zabarwić je czernią.\n\n Leba jest wciąż za młody, by popłynąć na wyspę z wieżą, ale świat nie chce czekać. Igrzyska na śmierć i życie, podczas których skrzydlaty chłopak odkryje, jakim siłom zacznie służyć po przejściu przez anomalię, to dopiero początek. Pełen poświęcenia i chęci czynienia dobra nie spodziewa się, że bogowie splotą jego los… z kłamcą i złodziejaszkiem. \n\nUważaj na to, co kradniesz. Może się bowiem okazać, że sięgasz po tożsamość piewcy, a jedyna pieśń, jaką usłyszysz, będzie śpiewana przez depczącą ci po piętach śmierć. Bren właśnie otworzył przed sobą drogę do lepszego życia. Nie spodziewa się, że ten szczęśliwy traf, który udało mu się wykantować bezczelnym kłamstwem, w jednej chwili może uczynić go najbardziej poszukiwanym zbiegiem w Estepii. Jego los byłby przesądzony, gdyby nie pewna anomalia i życzliwy głos rozsądku…. \n\nCzy odważysz się wejść do świata, w którym za magiczny talent zapłacisz kalectwem? Czy masz w sobie siłę, by jako wyrzutek przetrwać głęboko pod ziemią, wśród tajemniczych ścieżek miasta pradawnej rasy? Czy skonfrontujesz się z mrocznymi tropicielkami piewców? A może postawisz na ucieczkę? \n\n„Dar Anomalii” to zupełnie odmienna od dotychczasowych, wartka i nieoczywista opowieść o walce dobra ze złem oraz podszeptach skrzydlatych istot, które kierują ludzkimi losami… a może całkiem na odwrót?”. Magdalena Świerczek-Gryboś, pisarka, prezes zarządu Polskiej Fundacji Fantastyki Naukowej. \n\nKsięga I „Daru Anomalii” to zapowiedź znakomitego cyklu, który ma szansę podbić serca fanów oryginalnego, epickiego fantasy. Jest w tej powieści wszystko, co kochacie: fascynujący bohaterowie, z detalami budowany świat, wielka wojna o wszystko, oraz magia. Po lekturze nie będziecie mogli doczekać się kolejnych tomów. \n\nJakub Winiarski, pisarz, red. nacz. „Nowej Fantastyki” w latach 2010–2013",
        category: "fantasy, science fiction",
        type: "Zywkła",
        pages: 340,
        status1: "Nieprzeczytana",
        status2: "W trakcie czytania",
    },
    /* Second book */
    {
        id: 2,
        tittle: "Dar anomalii. Księga 2",
        author: "Paweł Zbroszczyk",
        coverImage: "/covers/id2.jpg",
        cost: 66.33,
        description: "Bezsenni to potężne istoty, które zsyłają magicznych posłańców, a ci wnoszą w światy brakujące pierwiastki dobra bądź zła.\n\n Nawet najwyżsi mogą jednak popełnić błąd\n\n.W Estepii wybucha gorączka taurynu. Rzadki kryształ jest cenniejszy od armii, władzy i koneksji, może uczynić posiadacza silniejszym od cesarza. Stanowi śmiertelne zagrożenie dla magicznie uzdolnionych – blokuje magię. Podczas gdy Bren i Leba wciąż uciekają przed piewcami, rozwijając nadnaturalne zdolności oraz odkrywając niewiarygodne miejsca Estepii i świata Parkan, Styks, przesiąknięty złem posłaniec, usiłuje zdobyć tauryn, by zagrozić cesarzowi. Ma również inny przerażający cel: nie spocznie, dopóki nie zgładzi wszystkich Bezsennych.\n\nW obliczu nadciągającej katastrofy Bren będzie musiał wziąć głęboki wdech i zanurzyć się w lodowate odmęty nieznanego. Czy w dawnym łotrze i złodziejaszku istnieje wystarczający pierwiastek dobra, by Estepia nie pogrążyła się w chaosie?\n\nCzytelnik ma świetne życie. To nie on musi się odważyć wraz z bohaterami, za to obserwuje, spija i ocenia. Pisarz natomiast zabawia się w stwórcę, wiedząc, że może się to skończyć uwielbieniem lub wzgardą. Paweł Zbroszczyk gra w tę grę absolutnie poważnie i bardzo umiejętnie. A upadki i wzloty jego postaci z każdym tomem sięgają bliżej gwiazd i głębiej w mrok.\n\nMagdalena Świerczek-Gryboś, redaktorka, pisarka, wielokrotnie nominowana do Nagrody Zajdla, Nagród Fantastyki w kategorii Nagroda im. Macieja Parowskiego\n\nJeżeli ktokolwiek miał wątpliwości co do talentu Zbroszczyka, Księga II „Daru anomalii” rozwieje je bardzo szybko. To znakomite fantasy, a autor jest z całą pewnością w czołówce tego gatunku w Polsce. Nie zdziwiłbym się, gdyby Netflix czy HBO ostrzyły już sobie zęby na ekranizację.\n\nJakub Winiarski, pisarz, red. nacz. „Nowej Fantastyki” w latach 2010-2013",
        category: "fantasy, science fiction",
        type: "zwykła",
        pages: 438,
        status1: "Nieprzeczytana",
        status2: "Nie w trakcie czytania",
    },
    /* Third book */
    {
        id: 3,
        tittle: "Dar anomalii. Księga 3",
        author: "Paweł Zbroszczyk",
        coverImage: "/covers/id3.jpg",
        cost: 66.33,
        description: "Z cyklu mądrości życiowe Pieprza: „Dobre uczynki są jak pierogi z jagodami. Napchasz nimi nawet największego wroga”.\n\nCzy stary gnom ma rację?\n\nPo pokonaniu Pernikokta i brawurowej ucieczce z wysp Szkarłatnej Królowej Bren oraz jego towarzysze znów są wolni. Chłopak pragnie odzyskać swojego przyjaciela Lebę i oddzielić Styksa od jego Parkanina za pomocą potężnego rozkazu. Niestety wiedzę o tym, jak go utworzyć, posiada najbardziej szalona osoba w Estepii.\n\nSpowite zdradliwym mrokiem podziemia i rozświetlone blaskiem kryształów miasta Yer Osti kryją więcej, niż ktokolwiek się spodziewa. Być może litość okazana niegdyś najpotężniejszym, dziś zdanym na cudzą łaskę istotom sprawi, że pośród wojennej pożogi nie runą mury ostatniej nadziei. A najważniejszą lekcją, jaką Bren otrzyma od losu, będzie ta dotycząca serca. Czasem nie ma nic trudniejszego, niż otworzyć je na innych pośród szerzącego się zła i dojmującego smutku żałoby.\n\nOto przed czytelnikami widowiskowe i pełne najpotężniejszej magii zwieńczenie trylogii Daru anomalii. Trzymajcie się mocno, bo to, co się wydarzy, może zrzucić nie tylko was z fotela, ale i niejedną koronę z głów władców mrocznego świata.\n\n„Czasem dobry uczynek to wyciągnięcie swej bratniej duszy z mroku i zwątpienia. A czasem rozdzielenie na zawsze. W życiu zło i dobro nigdy bowiem nie są czarno-białe... a przynajmniej w życiu bohaterów epickich opowieści. Możecie być pewni, że Paweł odrobił wszystkie lekcje debiutu, jego kontynuacji, i trzymacie w rękach zwieńczenie, które – jak wszystkie piękne historie – zostawi was z zachwytem i żalem, że to już koniec”.\n\nMagdalena Świerczek-Gryboś, redaktorka, pisarka\nwielokrotnie nominowana do Nagrody Zajdla, Nagród Fantastyki\nw kategorii Nagroda im. Macieja Parowskiego",
        category: "fantasy, science fiction",
        type: "Zwykła",
        pages: 550,
        status1: "Nieprzeczytana",
        status2: "Nie w trakcie czytania",
    },
    /* Fourth book */
    {
        id: 4,
        tittle: "Aniołowie zbrodni #1",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id4.jpg",
        cost: 24.99,
        description: "Trzynastoletnia Ray budzi się w piwnicy zamkniętego budynku. Pozbawiona wspomnień dziewczyna nie wie nawet, jak się tam znalazła. Kiedy szuka wyjścia, pojawia się przed nią chłopak owinięty bandażami. W ręku trzyma broń przypominającą kosę boga śmierci, którą chce zaatakować dziewczynkę… Co to za miejsce? Dlaczego ją tu zamknięto? Dla Ray rozpoczyna się właśnie\nśmiertelnie niebezpieczna ucieczka!",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Fifth book */
    {
        id: 5,
        tittle: "Aniołowie zbrodni #2",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id5.jpg",
        cost: 24.99,
        description: "Aby uciec z podziemia, pozbawiona wspomnień dziewczynka, Ray, i zabandażowany seryjny morderca, Zack, składają obietnicę, w której powierzają sobie swoje życia.\nNa piętrze B4 czeka na nich pomieszczenie wypełnione nagrobkami. Na jednym z nich widnieje imię Ray…",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Sixth book */
    {
        id: 6,
       tittle: "Aniołowie zbrodni #3",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id6.jpg",
        cost: 24.99,
        description: "Ray i Zack wreszcie docierają na piętro B3, zwane „kondygnacją pokuty”, którą kontroluje szalona strażniczka więzienna, Cathy. Próbując wydostać się z jej wymyślnych, sadystycznych pułapek, zostają zapędzeni w kozi róg. Czy w obliczu zbliżającej się śmierci będą w stanie dotrzymać danej sobie obietnicy?",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Seventh book */
    {
        id: 7,
       tittle: "Aniołowie zbrodni #4",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id7.jpg",
        cost: 24.99,
        description: "Hej, czy już nie pora, byście się pożegnali?\nWięzienna strażniczka, Cathy, zmusza Ray i Zacka do pokuty, próbując tym samym pokazać, jak krucha jest łącząca ich przysięga. Zack nie potrafi powstrzymać morderczych żądzy, które wywołał specyfik Cathy, i przystawia ostrze swojej kosy do szyi Ray!",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Eighth book */
    {
        id: 8,
       tittle: "Aniołowie zbrodni #5",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id8.jpg",
        cost: 24.99,
        description: "Zack i Ray w końcu stają twarzą w twarz z Cathy w pokoju egzekucji, gdzie czeka ich śmierć przez rozstrzelanie. Mając na celu poróżnienie Ray i Zacka, kobieta daje dziewczynce rewolwer. Oto ostatni etap B3, piętra „pokuty”! W tym tomie znajdziecie również opowiadanie przedstawiające przeszłość Cathy, do którego scenariusz napisał sam autor gry, Makoto Sanada.",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Ninth book */
    {
        id: 9,
       tittle: "Aniołowie zbrodni #6",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id9.jpg",
        cost: 24.99,
        description: "Ray udaje się samotnie w głąb B2, aby udowodnić swoją przydatność poważnie rannemu Zackowi. Rusza przed siebie, oczarowana przepełniającym to miejsce słodkim zapachem, który zdaje się prowadzić ją do miejsca, w którym czeka na nią duchowny Gray. Czy mężczyzna, który w celu ustalenia prawdziwej natury dziewczyny kwestionuje jej motywy, jest wrogiem czy przyjacielem…? Otwierają się wrota do B2, piętra ewaluacji głębi duszy!",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Tenth book */
    {
        id: 10,
       tittle: "Aniołowie zbrodni #7",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id10.jpg",
        cost: 24.99,
        description: "Po znalezieniu noża Zacka w jego pokoju, Ray wraca na B2, ale chłopaka już tam nie ma… Oniemiała, słyszy słowa Graya: „Jesteś źródłem tego łańcucha nieszczęść”. Gdy wreszcie obrady dobiegają końca, rozpoczyna się proces czarownicy, w którym wyjdzie na jaw prawda o Ray!",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Eleventh book */
    {
        id: 11,
       tittle: "Aniołowie zbrodni #8",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id11.jpg",
        cost: 24.99,
        description: "Po zakończonym procesie pastor Gray uznaje Ray za czarownicę. Przywiązana do krzyża zaczyna płonąć, lecz resztkami świadomości dostrzega Zacka, którego przecież nie powinno tam być…\n?W tym tomie znajdziecie dodatkowo historię z dzieciństwa Zacka!",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Twelfth book */
    {
        id: 12,
       tittle: "Aniołowie zbrodni #9",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id12.jpg",
        cost: 24.99,
        description: "Gdy nasi bohaterowie wchodzą do pierwszego pokoju na najwyższym piętrze, B1, Ray wydaje się być czymś wstrząśnięta i traci przytomność. Niedługo po tym pojawia się Danny, mając dla Zacka bardzo intrygującą opowieść.\n\n„Poznasz wszystkie jej sekrety”.\n\nPrzeszłość, którą Ray tak bardzo starała się ukryć, wreszcie ujrzy światło dzienne.",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Thirteenth book */
    {
        id: 13,
       tittle: "Aniołowie zbrodni #10",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id13.jpg",
        cost: 24.99,
        description: "Zack odkrył sekret piętra B1 i wyrusza o Ray, która właśnie się obudziła. „To ty zabijasz ludzi, którzy tu trafiają?”. W odpowiedzi słyszy jedynie przeszywający ciszę wystrzał…\n\nPrawdziwa i fałszywe uczucia, instynkt i rozsądek…\n\nW wirze sprzecznych emocji w dziewczynie budzą się mordercze żądze. Niczym za sprawą przeznaczenia, podnosi się kurtyna na scenie desperackiej walki o „obietnicę”.",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Fourteenth book */
    {
        id: 14,
       tittle: "Aniołowie zbrodni #11",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id14.jpg",
        cost: 24.99,
        description: "Zack i Rachel wznawiają poszukiwania i odkrywają nową, najwyższą kondygnację prowadzącą do wyjścia. Udało im się przedrzeć przez wszystkie piętra i podejmują temat tego, co ich czeka po ucieczce. Nagle jednak w akompaniamencie wybuchów rozbrzmiewa mechaniczne obwieszczenie, wywracając ich wymarzoną przyszłość do góry nogami…",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Fifteenth book */
    {
        id: 15,
       tittle: "Aniołowie zbrodni #12",
        author: "Sanada Makoto, Nazuka Kudan",
        coverImage: "/covers/id15.jpg",
        cost: 24.99,
        description: "Rachel spada podczas wybuchu bomby Danny’ego, a cały podziemny kompleks się zawala.\nTrzymając w swoich ramionach umierającą Ray, Zack otwiera drzwi na zewnątrz.\nWszystko w imię „przysięgi”…\nJedynie błękitny księżyc otacza swoim blaskiem tę dwójkę prącą przed siebie na przekór wszelkim przeszkodom, gdzie na końcu czeka ich…",
        category: "horror, thriller psychologiczny",
        type: "Manga",
        pages: 164,
        status1: "Przeczytana",
        status2: "",
    },
    /* Sixteenth book */
    {
        id: 16,
        tittle: "",
        author: "",
        coverImage: "/covers/id16.jpg",
        cost: 24.99,
        description: "",
        category: "",
        type: "",
        pages: 164,
        status1: "",
        status2: "",
    },
    /* Seventeenth book */
    {
        id: 17,
        tittle: "",
        author: "",
        coverImage: "/covers/id17.jpg",
        cost: 24.99,
        description: "",
        category: "",
        type: "",
        pages: 164,
        status1: "",
        status2: "",
    },
    /* Eighteenth book */
    {
        id: 18,
        tittle: "",
        author: "",
        coverImage: "/covers/id18.jpg",
        cost: 24.99,
        description: "",
        category: "",
        type: "",
        pages: 164,
        status1: "",
        status2: "",
    },
    /* Nineteenth book */
    {
        id: 19,
        tittle: "",
        author: "",
        coverImage: "/covers/id19.jpg",
        cost: 24.99,
        description: "",
        category: "",
        type: "",
        pages: 164,
        status1: "",
        status2: "",
    },
    /* Twentieth book */
    {
        id: 20,
        tittle: "",
        author: "",
        coverImage: "/covers/id20.jpg",
        cost: 24.99,
        description: "",
        category: "",
        type: "",
        pages: 164,
        status1: "",
        status2: "",
    },

];
export default books;